# config.yaml - scAR project parameter configuration
#liver
#pancrease
#pbmc
#main
# Input/output configuration
main_input_path: "data/pbmc/matrix.mtx"         # Input expression matrix path                        # Optional: csv, tsv, mtx, h5ad, loom, rds, npy
main_output_dir: "results"                        # Output directory
save_intermediate: false                    # Whether to save intermediate files (e.g. intermediate HDF5 files)

# Data reading parameters
batch_size: 2000                            # Number of cells read per batch (column chunk size)
csv_sep: ","                                # CSV file separator, change to "\t" for TSV
sparse_threshold: 0.001                     # Sparse gene filtering threshold (proportion of cells expressing the gene)

# Preprocessing parameters
binarization_threshold: 0.0                 # Expression > this value is marked as 1, otherwise 0

# GPU configuration
use_gpu: true                               # Whether to enable GPU
gpu_id: 0                                   # Which GPU device number to use

# Association rule metrics settings (whether to calculate)
metrics:
  support: true
  confidence: true
  lift: true
  leverage: true
  conviction: true

# Chunked calculation parameters (avoid OOM)
chunk_size: 1000                            # How many genes per chunk for conviction/lift and other metrics

thresholds:
  support: 0.01
  confidence: 0.6
  lift: 1.1
  leverage: 0.001
  conviction: 1.4







#liver
#pancrease
#pbmc

#go_and_kegg

# Input CSV file path, first and second columns are gene names
input_dir: "./DEG_and_results/pbmc"

# Species name, affects enrichment database selection, supports Human, Mouse, etc.
species: "Human"

# Number of genes for batch analysis, prevent resource occupation from analyzing too many at once
analysis_batch_size: 100

# Result save directory, GO and KEGG results will be placed here
output_dir: "./Enrichment_result"

# Gene set database used for GO enrichment analysis, can be replaced with other versions or categories
go_gene_sets:
  - "GO_Biological_Process_2021"

# Gene set database used for KEGG enrichment analysis
kegg_gene_sets:
  - "KEGG_2021_Human"

# Upper limit of significant pathways in final output, sorted by adjusted p-value
top_n: 10







#ppi
# config.py
ppi_output_dir: "./ppi_result"
# PPI file path
PPI_FILE : "interaction_data/ppi/PP-Decagon_ppi.csv"

# Whether has header
HAS_HEADER : False

# Visualization options (only suitable for small networks)
VISUALIZE : False

# Number of top hubs to output
TOP_HUB_NUM : 10

ppi_GENE_FILE : "data/pbmc/genes.tsv"
ppi_input_dir: "./results/pbmc"


#liver
#pancrease
#pbmc

# reactome
# AR data input directory
reactome_input_dir: "D:/software/code/code/scar2/results"

# Pathway mapping file
reactome_pathway_file: "D:/software/code/code/scar2/interaction_data/reactome/FIsInGene_070323_with_annotations.txt"

# Metrics list
metrics:
  - support
  - confidence
  - leverage
  - conviction
  - lift

# Result output directory
reactome_output_dir: "D:/software/code/code/scar2/reactome_results"

# Whether to filter significant P-values (P<0.05)
pvalue_threshold: 0.05

#tf
TF_input_dir: "D:/software/code/code/scar2/results"
TF_pathway_file: "D:/software/code/code/scar2/interaction_data/tf/new_kegg.human.reg.direction.txt"
TF_output_dir: "D:/software/code/code/scar2/TF_results"
sampling_interval : 5
filter_interval : 10
#liver
#pancrease
#pbmc

#degs
# Input data directory, must contain matrix.mtx / genes.tsv / barcodes.tsv
degs_data_dir: "./data/pancrease"

# Differential analysis parameters
de_method: "wilcoxon"      # Optional: t-test_overestim_var, wilcoxon, logreg
min_genes: 200             # Minimum number of genes expressed per cell
min_cells: 3               # Gene must be expressed in at least how many cells
normalize_target_sum: 1e4  # Normalization target sum

# Output directory
degs_output_dir: "./DEG_results"





#liver
#pancrease
#pbmc


#dges_and_results
assoc_rules_file: "./results/pbmc"
degs_file: "./DEG_results/pbmc"
output_base_dir: "./DEG_and_results"